name: Update index

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ums91/MyTv repository
      uses: actions/checkout@v3
      with:
        repository: ums91/MyTv
        token: ${{ secrets.TV_TOKEN }}

    - name: Checkout ums91/umsiptv repository
      uses: actions/checkout@v3
      with:
        repository: ums91/umsiptv
        token: ${{ secrets.TV_TOKEN }}
        path: umsiptv

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Run script to update m3u links
      run: |
        python fetch.py  # Assuming this script adds the content from MyTv/in.m3u to umsiptv/streams/index.m3u

    - name: Stage changes for commit
      run: |
        git add umsiptv/streams/index.m3u
        git status  # To verify the changes are staged

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -m "Update IPTV links in index.m3u"
        git push origin main
