name: Update IPTV Links

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight
  workflow_dispatch:

jobs:
  update_links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Ensure channel_log.txt exists if required by the script
      run: |
        touch channel_log.txt  # Create the file if it doesn't exist

    - name: Run IPTV fetch script
      run: python fetch_iptv_links.py  # Run the correct script

    - name: Stash any changes if present
      run: |
        git diff --quiet || git stash  # Stash any changes if there are any unstaged changes

    - name: Pull latest changes from remote
      run: |
        git pull origin main --rebase  # Fetch the latest changes and rebase

    - name: Apply stashed changes
      run: |
        git stash pop || echo "No stashed changes to apply"  # Apply stashed changes if any

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update IPTV links" || echo "No changes to commit"  # Commit changes if any
        git push origin main  # Push the changes after pull and rebase
      env:
        TV_TOKEN: ${{ secrets.TV_TOKEN }}
