name: Update IPTV Links

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-iptv-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and update IPTV links
      run: |
        python fetch_iptv_links.py  # Run your script to fetch and update the IPTV links

    - name: Commit and push changes
      run: |
        git config --global user.email "omargoroo91@gmail.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update IPTV links"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TV_TOKEN }}  # Use the TV_TOKEN secret for authentication
