name: Update IPTV Links

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ums91/MyTv repository
      uses: actions/checkout@v3
      with:
        repository: ums91/MyTv
        token: ${{ secrets.TV_TOKEN }}

    - name: Checkout ums91/umsiptv repository
      uses: actions/checkout@v3
      with:
        repository: ums91/umsiptv
        token: ${{ secrets.TV_TOKEN }}
        path: umsiptv

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies to install

    - name: Run script to update m3u links
      run: |
        python fetch.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add umsiptv/streams/index.m3u
        git commit -m "Update IPTV links"
        git push origin main
