name: IPTV Channel Validation

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour
  workflow_dispatch:  # Manual trigger

jobs:
  validate_channels:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Fetch IPTV links and validate them
      - name: Run IPTV Script
        run: |
          python fetch_iptv_links.py

      # Step 5: Check for changes and commit updates to the log file
      - name: Check for changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add channel_log.txt
          git status

      # Step 6: Commit and push changes if there are any
      - name: Commit and push changes
        run: |
          git commit -m "Update channel_log.txt with new data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TV_TOKEN }}  # Use your GitHub token secret for authentication
