name: Update IPTV Links

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  update_channels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Run IPTV update script
      run: |
        # Ensure channel_log.txt exists if it’s required for your script
        if [ ! -f "channel_log.txt" ]; then
          touch channel_log.txt
        fi
        python3 update_script.py

    - name: Commit changes
      run: |
        git add working_channels.m3u README.md channel_log.txt
        git commit -m "Update working channels and README with new links"
        git push
      env:
        TV_TOKEN: ${{ secrets.TV_TOKEN }}
