name: Update index.m3u with New Links

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:  

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MyTv repository
        uses: actions/checkout@v3
        with:
          repository: ums91/MyTv
          path: mytv

      - name: Checkout umsiptv repository
        uses: actions/checkout@v3
        with:
          repository: ums91/umsiptv
          path: umsiptv

      - name: Append new links from in.m3u to top of index.m3u
        run: |
          # Extract content from in.m3u
          new_content=$(cat mytv/in.m3u)
          
          # Add content at the top of index.m3u without overwriting
          echo -e "$new_content\n$(cat umsiptv/streams/index.m3u)" > umsiptv/streams/index.m3u

      - name: Commit and push changes
        run: |
          cd umsiptv
          git config --local user.name "GitHub Action"
          git config --local user.email "actions@github.com"
          git add streams/index.m3u
          git commit -m "Add new links from in.m3u to top of index.m3u"
          git push https://x-access-token:${{ secrets.TV_TOKEN }}@github.com/ums91/umsiptv.git
        env:
          TV_TOKEN: ${{ secrets.TV_TOKEN }}
