name: Update IPTV Links

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  update-iptv-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use the appropriate version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the IPTV update script
      run: |
        python fetch_iptv_links.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add working_channels.m3u README.md
        git commit -m "Update IPTV channels and README"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TV_TOKEN }}
