name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run IPTV script
      run: |
        python fetch_iptv_links.py

    - name: Commit and push updates to working_channels.m3u and README.md
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        
        # Add changes to git but exclude channel_log.txt (if you don't want to commit it)
        git add working_channels.m3u README.md
        
        # Check if there are changes to commit
        git diff --cached --quiet || git commit -m "Update working channels and README"
        
        # Push the changes
        git push
